[package]
name = "rust_xlsxwriter"
description = "A Rust module for writing files in the Excel 2007+ XLSX file format"
authors = ["John McNamara <jmcnamara@cpan.org>"]
homepage = "https://github.com/jmcnamara/rust_xlsxwriter"
repository = "https://github.com/jmcnamara/rust_xlsxwriter"
keywords = ["excel", "xlsx"]
readme = "README.md"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.3.0"
itertools = "0.10.0"

[dev-dependencies]
regex = "1.5.6"
pretty_assertions = "1"