[package]
name = "rust_xlsxwriter"
description = "A Rust module for writing files in the Excel 2007+ XLSX file format"
authors = ["John McNamara <jmcnamara@cpan.org>"]
keywords = ["excel", "xlsx"]
readme = "README.md"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
